export const locationData = {
  // --- Gujarat Major Cities ---
  "Ahmedabad": ["Navrangpura", "Satellite", "Prahlad Nagar", "Vastrapur", "Bopal", "Gotta", "Thaltej", "Bodakdev", "Maninagar", "Paldi"],
  "Surat": ["Adajan", "Vesu", "Varachha", "Piplod", "Katargam", "Udhna", "City Light", "Dumas", "Palanpur", "Rander"],
  "Vadodara": ["Alkapuri", "Akota", "Gotri", "Vasna Road", "Sayajigunj", "Manjalpur", "Karelibaug", "Waghodia Road"],
  "Rajkot": ["Kalavad Road", "University Road", "Nana Mava", "Kotecha Chowk", "Race Course Road", "Raiya Road", "Bhakti Nagar"],
  "Gandhinagar": ["Sector 11", "Sector 21", "Infocity", "Sargasan", "Kudasan", "Raisan", "Pethapur", "Sector 7"],
  "Bhavnagar": ["Waghawadi Road", "Kaliyabid", "Hill Drive", "Vidhyanagar", "Chitra", "Ghogha Circle"],
  "Jamnagar": ["Digjam Circle", "Khodiyar Colony", "Park Colony", "Patel Colony", "Aerodrome Road", "Windmill Area"],
  "Junagadh": ["Zanzarda Road", "Joshipura", "Talav Gate", "Kalwa Chowk", "Motibaug", "Mendarda Road"],
  "Anand": ["Vallabh Vidyanagar", "Karamsad Road", "Borsad Chowkdi", "Bakrol", "Nana Bazar"],
  "Navsari": ["Lunsikui", "Vijalpore", "Sayaji Road", "Kabilpore", "Eru Char Rasta"],
  "Morbi": ["Ravapar Road", "Sanala Road", "Shakti Plot", "Mahendranagar", "Lati Plot"],
  "Nadiad": ["College Road", "Santram Mandir Area", "Mission Road", "Pij Road", "Vaniavad"],
  "Bharuch": ["Zadeshwar", "Bholav", "GNFC Township", "Shravan Chowkdi", "Link Road"],
  "Mehsana": ["Modhera Road", "Radhanpur Road", "Highway Area", "Panchot Circle"],
  "Bhuj": ["Station Road", "Mirzapar Road", "Madhapar", "Mundra Road", "Hospital Road"],
  "Porbandar": ["MG Road", "Chhaya", "Khapat", "Zaveri Bazar"],
  "Valsad": ["Tithal Road", "Dharampur Road", "Atul", "Abrama"],
  "Vapi": ["GIDC", "Chala", "Gunjan", "Vapi Town", "Silvassa Road"],
  "Gondal": ["Station Plot", "Marketing Yard Area", "Kailashbagh"],
  "Palanpur": ["Abu Road", "Deesa Highway", "Becharpura"],
  "Amreli": ["Station Road", "Chital Road", "Lathi Road"],
  "Surendranagar": ["Wadhwan", "Ratanpar", "Dudhrej"],

  // --- Other Major Indian Cities ---
  "Bangalore": ["HSR Layout", "Indiranagar", "Koramangala", "Whitefield", "BTM Layout", "Jayanagar", "Electronic City", "JP Nagar"],
  "Mumbai": ["Bandra West", "Andheri West", "Powai", "Worli", "Juhu", "Colaba", "Borivali", "Goregaon", "Malad", "Dadar"],
  "Delhi": ["Hauz Khas", "Greater Kailash", "Rohini", "Connaught Place", "Dwarka", "Saket", "Vasant Kunj", "Karol Bagh", "Lajpat Nagar"],
  "Pune": ["Kothrud", "Baner", "Viman Nagar", "Hinjewadi", "Magarpatta", "Kalyani Nagar", "Hadapsar", "Wakad", "Aundh"],
  "Hyderabad": ["Gachibowli", "Hitech City", "Banjara Hills", "Jubilee Hills", "Kukatpally", "Madhapur", "Manikonda", "Kondapur"],
  "Chennai": ["Adyar", "Anna Nagar", "Besant Nagar", "Mylapore", "T Nagar", "Velachery", "Nungambakkam", "Thiruvanmiyur"],
  "Kolkata": ["Salt Lake", "New Town", "Ballygunge", "Park Street", "South City", "Dum Dum", "Behala", "Jadavpur"],
  "Jaipur": ["Malviya Nagar", "Vaishali Nagar", "Mansarovar", "C-Scheme", "Raja Park", "Bani Park", "Jagatpura", "Tonk Road"],
  "Lucknow": ["Gomti Nagar", "Aliganj", "Hazratganj", "Indira Nagar", "Jankipuram", "Mahanagar", "Aashiana", "Vikas Nagar"],
  "Indore": ["Vijay Nagar", "Saket", "Old Palasia", "New Palasia", "Rajendra Nagar", "Bhawarkua", "Mahalakshmi Nagar"],
  "Gurugram": ["DLF Phase 1", "DLF Phase 5", "Sushant Lok", "Golf Course Road", "Sohna Road", "Sector 56", "Cyber City"],
  "Noida": ["Sector 15", "Sector 18", "Sector 62", "Sector 137", "Noida Extension", "Sector 93", "Sector 50"]
};
