"""Added Gender Field

Revision ID: 08ddcf447ead
Revises: 8906f7048910
Create Date: 2026-04-30 17:52:57.435605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ddcf447ead'
down_revision = '8906f7048910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column('gender', sa.String(length=10), nullable=False, server_default='male')
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
