"""add is_profile_complete to user

Revision ID: 3f7d9f8a8a3b
Revises: 6b4088cf0661
Create Date: 2026-05-04 17:18:42.417463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7d9f8a8a3b'
down_revision = '6b4088cf0661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_profile_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_profile_complete')

    # ### end Alembic commands ###
