"""Implemented diverged profile and property models

Revision ID: 555f6075b580
Revises: 88033966eece
Create Date: 2026-05-04 15:36:27.838538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555f6075b580'
down_revision = '88033966eece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('rent_amount', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type_pref', sa.String(length=50), nullable=True))
        batch_op.alter_column('preferred_areas',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('current_city')
        batch_op.drop_column('room_type')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_city', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('preferred_areas',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('room_type_pref')

    op.drop_table('properties')
    # ### end Alembic commands ###
