"""add_occupancy_to_property

Revision ID: 6b7f70800fd5
Revises: 416297665ad0
Create Date: 2026-05-13 16:11:51.533243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7f70800fd5'
down_revision = '416297665ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupancy_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('occupancy_count')

    # ### end Alembic commands ###
