"""Added user types and profiles

Revision ID: 88033966eece
Revises: 08ddcf447ead
Create Date: 2026-05-04 15:15:06.867253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88033966eece'
down_revision = '08ddcf447ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('current_city', sa.String(length=100), nullable=True),
    sa.Column('preferred_areas', sa.String(length=255), nullable=True),
    sa.Column('sleep_schedule', sa.String(length=50), nullable=True),
    sa.Column('cleanliness', sa.String(length=50), nullable=True),
    sa.Column('guests_policy', sa.String(length=50), nullable=True),
    sa.Column('smoking', sa.String(length=20), nullable=True),
    sa.Column('drinking', sa.String(length=20), nullable=True),
    sa.Column('pets', sa.String(length=20), nullable=True),
    sa.Column('food_habits', sa.String(length=50), nullable=True),
    sa.Column('noise_level', sa.String(length=50), nullable=True),
    sa.Column('work_from_home', sa.String(length=50), nullable=True),
    sa.Column('min_budget', sa.Integer(), nullable=True),
    sa.Column('max_budget', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('move_in_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('budget')
        batch_op.drop_column('occpation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occpation', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_login')
        batch_op.drop_column('status')
        batch_op.drop_column('role')
        batch_op.drop_column('user_type')
        batch_op.drop_column('occupation')

    op.drop_table('profiles')
    # ### end Alembic commands ###
