"""Added profile Fiedls

Revision ID: 8906f7048910
Revises: 117a17d1bf15
Create Date: 2026-04-30 16:07:17.613542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8906f7048910'
down_revision = '117a17d1bf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occpation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('occpation')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
